* *-metrics

* Introduction

Sources for Philosometrics and Musimetrics works.

* Directories

- src/      source
- txt/      tex files

* Using

  In the src/v3 directory, uncomment the desired lines to your data set
  on file final4d.py and run:

  #+BEGIN_SRC sh
$ python final4d.py > output.txt
  #+END_SRC

  The results are g1.eps and output.txt. Check the manuscripts for details
  about results interpretation.

  An interesting file is valida_metricas2d.py. It explains how point-to-line
  was implemented and generalized to point-to-hiperplane, used at dialetics
  calculation.

* Results

  Last interesting results are:

  - src/v3/results_feb29/composers for composers
  - src/v3/results_feb29/philosophers for philosophers

  These results were used to the last versions of manuscripts:

  - txt/musimetrics/musimetrics.(tex,pdf)
  - txt/philosometrics/phi4.(tex,pdf)

* References

Good references to point-hiperplane distance calc:

- http://www.ualberta.ca/MATH/gauss/fcm/LinAlg/InRn/DotPrdct/DstncePntHprpln.htm
- http://www.ualberta.ca/MATH/gauss/fcm/LinAlg/InRn/DotPrdct/DstncePntHprpln_exrcss.htm
- http://www.ualberta.ca/MATH/gauss/fcm/LinAlg/InRn/DotPrdct/DstncePntHprplnExrcs1a_fullsltn.htm

* Authors

Instituto de Fisica de Sao Carlos - IFSC
Universidade de Sao Paulo - USP

- Prof. Luciano da Fontoura Costa <ldfcosta@gmail.com>
- Renato Fabbri <renato.fabbri@gmail.com>
- Vilson Vieira <vilson@void.cc>

2011/2012
